Allow the library and CUPL compiler options to be overriden.

diff --git a/linux-workflow/5vcomp b/linux-workflow/5vcomp
--- a/linux-workflow/5vcomp
+++ b/linux-workflow/5vcomp
@@ -1,15 +1,27 @@
 #!/bin/sh
 
-CUPL_DEFAULT_OPTIONS="m1jn" #These are the options that will be passed to the CUPL.EXE compiler
-CUPL_SIMULATION_OPTIONS="sw" #These options are added only if an .SI file is found.
+#This script is a small wrapper around the CUPL compiler -- avoiding common pitfalls and setting sensible default options.
 
-#This is the device library CUPL will use. We're assuming you're using whatever comes with Atmel WinCUPL, however, if you have device libraries from other packages (like PLDmaster from Logical Devices, you may be able to target other devices).
+#This section is concerned with the device library CUPL will use. We're assuming you're using what comes with Atmel WinCUPL (Atmel.dl), however,
+#if you have device libraries from other packages (like PLDmaster from Logical Devices, you may be able to target other / obsolete devices).
 #We're not covering other devices outside of the Atmel Library simply because none seem to be active parts anymore, but, this is how you'd do it if you wanted to.
-DEVICE_LIB="c:/Wincupl/Shared/Atmel.dl" #The library provided by Atmel WinCUPL
 
-#DEVICE_LIB="c:/Wincupl/Shared/totaldes.dl" #The library provided by Total Designer
-#DEVICE_LIB="c:/Wincupl/Shared/pldmstr.dl" #The library provided by PLDmaster
-#DEVICE_LIB="c:/Wincupl/Shared/palxprt.dl" #The library provided by PALexpert
+#If you want to override you can set DEVICE_LIB in your .profile, or at runtime like this:
+#    DEVICE_LIB="c:/Wincupl/Shared/pldmstr.dl" 5vcomp yourfile.pld
+
+#Or you could uncomment one of the below lines and risk it being overwritten by an update.
+#DEVICE_LIB="c:/Wincupl/Shared/Atmel.dl" #The library provided by Atmel WinCUPL from either 3/31/04 or 10/24/00
+#DEVICE_LIB="c:/Wincupl/Shared/totaldes.dl" #The library provided by Total Designer from 8/14/99
+#DEVICE_LIB="c:/Wincupl/Shared/pldmstr.dl" #The library provided by PLDmaster from 2/21/00
+#DEVICE_LIB="c:/Wincupl/Shared/palxprt.dl" #The library provided by PALexpert from 6/20/99
+
+DEFAULT_DEVICE_LIB="c:/Wincupl/Shared/Atmel.dl" #Do not change this.
+
+#You can override the options passed to CUPL here by either
+#Seting CUPL_OPTIONS at rutime, setting it in your environment (.profile), or by uncommenting below (and risking it being overwritten with an update):
+#CUPL_OPTIONS="m1jn"
+CUPL_DEFAULT_OPTIONS="m1jn" #These are the options that will be passed to the CUPL.EXE compiler if not explicitly set in CUPL_OPTIONS.
+CUPL_SIMULATION_OPTIONS="sw" #These options are added only if an .SI file is found and no CUPL options have been explicitly set.
 
 #A summary of the most relevant/important options to CUPL is here. See documentation for a full list/explanation.
 #
@@ -23,8 +35,8 @@ DEVICE_LIB="c:/Wincupl/Shared/Atmel.dl" #The library provided by Atmel WinCUPL
 # -b create berkeley pla format
 # -e create expanded macro definitions
 #
-# -s run simulation. Expects a .SI file to be present, generates an .SO file. If -j is specified, will append test vectors to the .JED file. Automatically implies -a generation of an .ABS file.
-# -w run simulation. Expects a .SI file to be present, genrates a .w file. Automatically implies -a generation of an .ABS file.
+# -s run simulation; create a .SO file. Expects a .SI file to be present. If -j is specified, will append test vectors to the .JED file. Automatically implies -a generation of an .ABS file.
+# -w run simulation; create a .W file.  Expects a .SI file to be present, Automatically implies -a generation of an .ABS file.
 
 #Known issues:
 #we should probably insist that the find150x.exe files be replaced with the corresponding fit150x.exe files in the fitters directory. This might be preventing the fitters from being called automatically when working with CPLD parts that use a fitter.
@@ -35,9 +47,9 @@ CYN='\033[1;36m'
 YEL='\033[1;33m'
 NC='\033[0m' # No Color
 
-printf "\n${CYN}5vpld CUPL Compiler Helper - A light wrapper on top of CUPL.EXE${NC}\n\n"
+printf "${CYN} = 5vpld CUPL Compiler Helper - A light wrapper on top of CUPL.EXE = ${NC}\n\n"
 
-echo $1
+#echo $1
 
 #Standard error regarding prerequisites
 prerequisite_error()
@@ -55,11 +67,18 @@ prerequisite_error()
 
 pause_before_exit()
 {
-    echo "Press enter to exit"
+    printf "\nPress enter to exit"
     read a
 }
 
-#: <<'END'
+if [ $# -ne 1 ]; then #Show 5vcomp script usage message if we weren't passed a file.
+    printf "USAGE: Please pass the name of a .PLD file to be compiled. Example:\n"
+    printf "${YEL}5vcomp COUNTER.PLD${NC}\n\n"
+    printf "This script will attempt to compile it using reasonable defaults passed to CUPL.EXE\n"
+    printf "Additionally, DEVICE_LIB and CUPL_OPTIONS can be set as environment variables if defaults are not acceptable"
+    pause_before_exit
+    exit 1
+fi
 
 #We check the version of Wine installed:
 WINE_VERSION=`wine --version`
@@ -68,7 +87,20 @@ if [ $? -ne 0 ]; then
     prerequisite_error
 fi
 
-#We check to see if the latest known version of fitters are installed.
+if [ -z "${DEVICE_LIB}" ]; then #If the device library has not been explicitly specified, use the default Atmel.dl
+    echo "INFO: Using default Atmel.dl Device Library"
+    DEVICE_LIB=${DEFAULT_DEVICE_LIB}
+else
+    echo "INFO: Using device library explicitly defined in: DEVICE_LIB=${DEVICE_LIB}"
+fi
+
+if [ ! -f `WINEDEBUG="fixme-hid" winepath -u "${DEVICE_LIB}"` ]; then
+    printf "${RED} * ERROR: Could not find device library in path: ${DEVICE_LIB}${NC}\n"
+    pause_before_exit
+    exit 1
+fi
+
+#We check to see if the latest known version of fitters are installed. The original Atmel fitters included with WinCUPL are old.
 FIT1502PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1502.exe"`
 FIT1504PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1504.exe"`
 FIT1508PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1508.exe"`
@@ -97,37 +129,41 @@ fi
 
 if [ $SUMFAIL = "true" ]; then
     printf "${RED}ERROR: Fitter version incorrect.${NC}\n"
-    echo "\nIt looks like you might be using the original fitters that came with WinCUPL.\nPlease extract and replace the fitters with the latest from:"
-    echo "https://ww1.microchip.com/downloads/en/DeviceDoc/ProChip5.0.1.zip"
-    echo "They should identify as \"Version 1918 (3-21-07)\" when run from the command line:"
+    echo " * It looks like you might be using the original fitters that came with WinCUPL."
+    echo "   * Please replace the fitters located in c:/Wincupl/WinCupl/Fitters/ with the latest ones from Atmel Prochip."
+    echo "     * This can either be done by:"
+    echo "       * Installing Atmel Prochip and pulling the files from C:\ATMEL_PLS_Tools\Prochip\PLDFit"
+    echo "       * Using innoextract on ProChip5_setup.exe"
+    echo "     * https://ww1.microchip.com/downloads/en/DeviceDoc/ProChip5.0.1.zip"
+    echo " * The fitters should identify as \"Version 1918 (3-21-07)\" when run from the command line."
+    echo " * You should also delete every find150X.exe file and replace it with a copy of the corresponding fit150X.exe file."
     prerequisite_error
 fi
 
 
-if [ $# -ne 1 ] #Make sure we passed options to CUPL.EXE
-  then
-    printf "USAGE: Please pass the name of a .PLD file to be compiled. Ex:\n"
-    printf "${YEL}5vcomp COUNTER.PLD${NC}\n\n"
-    printf "This script will attempt to compile it using reasonable defaults passed to CUPL.EXE\n\n"
+#Since the Atmel fitter will include the whole file path in an EDIF when when requested to create one, it will contain invalid characters. Instead, we switch to the containing directory of the file we are passed.
+cd "$(dirname "$1")"
+if [ $? -ne 0 ]; then
+    printf "${RED}ERROR: Failed to change to directory $(dirname "$1")${NC}\n"
     pause_before_exit
     exit 1
 fi
+#echo "Current Directory is:"
+#pwd
 
-#END
-
-FILENAME=$1
+FILENAME=$(basename "$1")
 
 #Since CUPL.EXE accepts files with or without a file extension, we try to do the same and append the extension if necessary.
 #We'd simply pass $1 directly to CUPL.EXE but we really want to identify the actual filename as the length is important (too long or multiple periods and it breaks CSIM.EXE).
-if [ ! -f "$1" ]; then
-    if [ -f "${1}.pld" ]; then
-	printf "${GRN}Appending .pld to input filename.${NC}\n"
-        FILENAME="$1.pld"
+if [ ! -f "${FILENAME}" ]; then
+    if [ -f "${FILENAME}.pld" ]; then
+	printf "INFO: Appending .pld to input filename.${NC}\n"
+        FILENAME="${FILENAME}.pld"
         continue
     fi
-    if [ -f "${1}.PLD" ]; then
-	printf "${GRN}Appending .PLD to input filename.${NC}\n"
-        FILENAME="$1.PLD"
+    if [ -f "${FILENAME}.PLD" ]; then
+	printf "INFO: Appending .PLD to input filename.${NC}\n"
+        FILENAME="${FILENAME}.PLD"
         continue
     fi
 fi
@@ -138,33 +174,42 @@ if [ ! -f "${FILENAME}" ]; then
     exit 1
 fi
 
-FILENAME_NOPATH=`basename ${FILENAME}`
+#FILENAME=$(basename "$1")
+#FILENAME_NOPATH=`basename ${FILENAME}`
 
 #Too long filenames is a horrible bug in CSIM.EXE that took forever to figure out.
-if [ ${#FILENAME_NOPATH} -gt 19 ]; then
+if [ ${#FILENAME} -gt 19 ]; then
     printf "${RED}ERROR: Filenames longer than 19 total characters cause problems with CSIM.EXE\nUse 15 characters max for filename + 1 dot + 3 file extension.${NC}\n"
     pause_before_exit
     exit 1
 fi
 
 #Multiple periods in the filename also cause CSIM.EXE to break.
-if [ `echo ${FILENAME_NOPATH} | grep -o "\." | wc -l` -gt 1 ]; then
+if [ `echo ${FILENAME} | grep -o "\." | wc -l` -gt 1 ]; then
     printf "${RED}ERROR: Filenames containing more than one period cause problems with CSIM.EXE\nFilenames should only contain 1 period.${NC}\n"
     pause_before_exit
     exit 1
 fi
 
+#Filenames containing spaces will cause Atmel Fitter Generated EDIF files to have spaces in them, which is invalid EDIF.
+if [ `echo ${FILENAME} | grep -o " " | wc -l` -gt 0 ]; then
+    printf "${RED}WARNING: Filenames containing spaces cause problems with any EDIF files that are generated. Continuing Anyway...${NC}\n"
+fi
+
+
 BASEFILENAME=${FILENAME%.*} #This strips off the file extension
 
-
-#If we detect a corresponding .SI file, then we pass the -s and -w options to CUPL.EXE so that simulation is performed.
-if [ -f "${BASEFILENAME}.SI" ]; then
-    SIMFILENAME="${BASEFILENAME}.SI"
-elif [ -f "${BASEFILENAME}.si" ]; then
-    SIMFILENAME="${BASEFILENAME}.si"
+#Determine the options we'll use for the CUPL Compiler. If none are explicitly specified, we use sensible defaults.
+if [ -z "${CUPL_OPTIONS}" ]; then
+    CUPL_OPTIONS=${CUPL_DEFAULT_OPTIONS}
+    #If we detect a corresponding .SI file, then we add on the -s and -w options as well so that simulation is performed.
+    if [ -f "${BASEFILENAME}.SI" -o -f "${BASEFILENAME}.si" ]; then
+        CUPL_OPTIONS=${CUPL_OPTIONS}${CUPL_SIMULATION_OPTIONS}
+    else
+        echo "INFO: Corresponding .SI input file not found. Simulation / Test vector generation will not be performed."
+    fi
 else
-    echo "WARNING: Corresponding .SI input file not found. Simulation / Test vector generation will not be performed."
-    CUPL_SIMULATION_OPTIONS=""
+    echo "Using compiler options explicitly specified: ${CUPL_OPTIONS}"
 fi
 
 #If we are passed a path along with the filename, we need to turn it into something CUPL.EXE will recognize
@@ -172,15 +217,23 @@ FILENAME_FULLPATH=`WINEDEBUG="fixme-hid" winepath -w "${1}"`
 
 #Time to run CUPL.EXE
 printf "${GRN}Running CUPL.EXE with the following command line: ${NC}\n"
-echo "${YEL}c:/Wincupl/Shared/cupl.exe -${CUPL_DEFAULT_OPTIONS}${CUPL_SIMULATION_OPTIONS} -u ${DEVICE_LIB} ${FILENAME_FULLPATH}${NC}"
+echo "${YEL}c:/Wincupl/Shared/cupl.exe -${CUPL_OPTIONS} -u ${DEVICE_LIB} ${FILENAME}${NC}"
 echo "\n"
 #We supress the most common wine debug warnings as none have been found to create issues with CUPL. There is still one "fixme:imm" that seems to be coming from a child process.
-WINEDEBUG="fixme-hid,fixme-ntdll,fixme-imm" wine c:/Wincupl/Shared/cupl.exe -${CUPL_DEFAULT_OPTIONS}${CUPL_SIMULATION_OPTIONS} -u ${DEVICE_LIB} ${FILENAME_FULLPATH}
+WINEDEBUG="fixme-hid,fixme-ntdll,fixme-imm" wine c:/Wincupl/Shared/cupl.exe -${CUPL_OPTIONS} -u ${DEVICE_LIB} "${FILENAME}"
 
 if [ $? -eq 0 ]; then
     printf "${GRN}SUCCESS: CUPL returned successfully.${NC}\n"
-    printf "${GRN}A .JED file should have been produced, which can be used to program the target device.${NC}\n"
-    sleep 3
+    printf "${GRN} * A .JED file should have been produced, which can be used to program the target device.${NC}\n"
+    if [ -f "${BASEFILENAME}.edn" ]; then
+        printf "INFO: An EDIF file has been detected.\n * In the future, we may process this further using Spydrnet to either convert to a Graphviz visualization or to generate verilog.\n"
+        EDIF2V_LOC=`which edif2v.py`
+        if [ $? -eq 0 ]; then
+            printf " * Trying to create a verilog file..."
+            python3 ${EDIF2V_LOC} ${BASEFILENAME}.edn
+        fi
+    fi
+    sleep 2
 else
     printf "${RED}ERROR: CUPL returns a non-zero exit code: ${?}${NC}\n"
     if [ -n ${CUPL_SIMULATION_OPTIONS} ]; then
